export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAIL = "GET_POSTS_FAIL";

export const GET_POST_DETAIL_REQUEST = "GET_POST_DETAIL_REQUEST";
export const GET_POST_DETAIL_SUCCESS = "GET_POST_DETAIL_SUCCESS";
export const GET_POST_DETAIL_FAIL = "GET_POST_DETAIL_FAIL";
export const GET_POST_DETAIL_RESET = "GET_POST_DETAIL_RESET";
