export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_SUCCESS_AND_FINISH = "GET_POSTS_SUCCESS_AND_FINISH";
export const GET_POSTS_FAIL = "GET_POSTS_FAIL";
export const GET_POSTS_RESET = "GET_POSTS_RESET";

export const GET_POST_DETAIL_REQUEST = "GET_POST_DETAIL_REQUEST";
export const GET_POST_DETAIL_SUCCESS = "GET_POST_DETAIL_SUCCESS";
export const GET_POST_DETAIL_FAIL = "GET_POST_DETAIL_FAIL";
export const GET_POST_DETAIL_RESET = "GET_POST_DETAIL_RESET";

export const POST_CREATE_REQUEST = "POST_CREATE_REQUEST";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAIL = "POST_CREATE_FAIL";
export const POST_CREATE_RESET = "POST_CREATE_RESET";

export const GET_MOST_VIEWS_POSTS_REQUEST = "GET_MOST_VIEWS_POSTS_REQUEST";
export const GET_MOST_VIEWS_POSTS_SUCCESS = "GET_MOST_VIEWS_POSTS_SUCCESS";
export const GET_MOST_VIEWS_POSTS_FAIL = "GET_MOST_VIEWS_POSTS_FAIL";

export const SEARCH_POSTS_REQUEST = "SEARCH_POSTS_REQUEST";
export const SEARCH_POSTS_SUCCESS = "SEARCH_POSTS_SUCCESS";
export const SEARCH_POSTS_FAIL = "SEARCH_POSTS_FAIL";
export const SEARCH_POSTS_RESET = "SEARCH_POSTS_RESET";

export const ADD_NEW_POST_TO_EXIST_POSTS = "ADD_NEW_POST_TO_EXIST_POSTS";
export const SET_INFINITY_SKIP_COUNT = "SET_INFINITY_SKIP_COUNT";
export const SET_FIRST_RENDER = "SET_FIRST_RENDER";

export const GET_POSTS_BY_TAG_REQUEST = "GET_POSTS_BY_TAG_REQUEST";
export const GET_POSTS_BY_TAG_SUCCESS = "GET_POSTS_BY_TAG_SUCCESS";
export const GET_POSTS_BY_TAG_FAIL = "GET_POSTS_BY_TAG_FAIL";
export const GET_POSTS_BY_TAG_RESET = "GET_POSTS_BY_TAG_REQUEST";
